### ISSUE TITLE
Cannot find the path when absolute path contain whitespace.

### ISSUE THREAD

**Issue by KarolBartyzel** [kevinwolfcr/expo-enable-hooks#1]
Logs: 
cp: target 'MYPATH WITH SPACE\node_modules\react-native\Libraries\Renderer' is not a directory
❌  Error: Command failed: cp -R MYPATH WITH SPACE\node_modules\@kevinwolf\expo-enable-hooks\lib/rn-renderer/* MYPATH WITH SPACE\node_modules\react-native\Libraries\Renderer

**Comment by kevinwolfcr** [comment]
fixed in #2
